M48
; DRILL file {KiCad (6.0.8)} date Mon Oct 24 12:17:14 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-24T12:17:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X5.1024Y-4.0866
X5.1024Y-4.878
X5.4488Y-4.0866
X5.4488Y-4.878
T2
X4.685Y-4.4409
T0
M30
